export const modelos = [
  "audi r8",
  "chevrolet aveo",
  "chevrolet camaro",
  "chevrolet suburban",
  "dmc delorean",
  "ferrari f8 tributo",
  "hyundai atos",
  "jeep wrangler",
  "mini cooper",
  "nissan tsuru",
  "nissan versa",
  "rollsroyce phantom",
  "tesla cybertruck",
  "tesla model x",
  "volkswagen beatle",
  "volkswagen jetta",
]